[package]
name = "Melquiades"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.10"
softbuffer = "0.4"
winit = "0.29"


[target.'cfg(target_os = "linux")'.dependencies]
linuxvideo = "0.3.5"
pipewire = "0.10.1"
zbus = "5.19.0"
ashpd = { version = "0.13.13", features = ["screencast"] }
tokio = { version = "1", features = ["rt-multi-thread"] }


[target.'cfg(target_os = "macos")'.dependencies]
screencapturekit = "9.0.1"
